name: .NET Framework 4.8 Build

on:
  schedule:
    - cron: '0 0 * * 0'

  workflow_dispatch:
    inputs:
      publish:
        description: Skip version check and publish release
        type: boolean
        required: false
        default: false

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Manual Clone Repository
      shell: bash
      run: |
        # Use the GITHUB_TOKEN for authentication
        git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git .
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Get current date
      id: date
      shell: bash
      run: echo "date=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_OUTPUT

    - name: Checkout all submodules
      id: update_sync
      shell: bash
      run: |
        git submodule update --init --recursive --remote --merge
        if [ -n "$(git status --porcelain --ignore-submodules=dirty)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
          echo "No changes detected."
        fi

    - name: Push Updated History
      if: ${{ steps.update_sync.outputs.changed == 'true' }}
      shell: bash
      run: |
        UPDATED_FILES=$(git diff --name-only --diff-filter=M | sed 's/^/- /')
        COMMIT_MSG=$(printf "[${{ steps.date.outputs.date }}] Build: Updated packages.\n$UPDATED_FILES")
        git add .
        git commit -m "$COMMIT_MSG"
        git push origin main

    - name: Install DNF 4.8 packs
      shell: pwsh
      if: ${{ steps.update_sync.outputs.changed == 'true' || github.event.inputs.publish == 'true' }}
      working-directory: "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer"
      run: |
        $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
        $WorkLoads = '--add Microsoft.Net.Component.4.8.SDK --add Microsoft.Net.Component.4.8.TargetingPack --add Microsoft.Net.ComponentGroup.4.8.DeveloperTools'
        $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"", $WorkLoads, $WorkLoads, '--quiet', '--norestart', '--nocache')
        $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      if: ${{ steps.update_sync.outputs.changed == 'true' || github.event.inputs.publish == 'true' }}
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
      if: ${{ steps.update_sync.outputs.changed == 'true' || github.event.inputs.publish == 'true' }}

    - name: Build Solution
      if: ${{ steps.update_sync.outputs.changed == 'true' || github.event.inputs.publish == 'true' }}
      shell: bash
      run: |
        set -x
        PWDROOT=$(pwd -P)
        mkdir -p ./Artifacts
        for pkg in Certify ForgeCert Koh Lockless RestrictedAdmin Rubeus SafetyKatz Seatbelt SharpDPAPI SharpDump SharpUp SharpWMI Snaffler # Skipping KeeThief/DecryptionShellcode KeeThief/KeeTheft KeeThief/KeePass-2.34-Source-Patched
        do
          cd $pkg
          if [[ "$pkg" == "Snaffler" ]]; then
            msbuild.exe Snaffler.sln -t:restore -p:Configuration=Release -p:RestorePackagesConfig=true
          else
            msbuild.exe -t:restore -p:Configuration=Release -p:RestorePackagesConfig=true
          fi
          find . -name "*.csproj" -exec sed -i 's/<TargetFrameworkVersion>v.*<\/TargetFrameworkVersion>/<TargetFrameworkVersion>v4.8<\/TargetFrameworkVersion>/' {} +
          find . -name "*.csproj" -exec sed -i 's|</Project>||' {} + -exec sed -i '$r ../obfuscar-template.patch' {} + -exec sed -i '$a </Project>' {} +
          
          if [[ "$pkg" == "Snaffler" ]]; then
            nuget restore Snaffler.sln
            msbuild.exe Snaffler.sln -p:Configuration=Release -p:DebugType=None -p:DebugSymbols=false
          else
            nuget restore *.sln
            msbuild.exe *.sln -p:Configuration=Release -p:DebugType=None -p:DebugSymbols=false
          fi

          cd ${pkg}/bin/Release
          
          shopt -s nullglob
          for file in *.exe
          do
            cp "$file" "${PWDROOT}/Artifacts/${file%.exe}-NoObfs.exe"
          done

          for file in *.dll
          do
            cp "$file" "${PWDROOT}/Artifacts/${file%.dll}-NoObfs.dll"
          done

          for file in ./Obfuscator_Output/*
          do
            cp $file "${PWDROOT}/Artifacts/"
          done
          shopt -u nullglob
          
          cd $PWDROOT
        done

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: ${{ steps.update_sync.outputs.changed == 'true' || github.event.inputs.publish == 'true' }}
      with:
        tag_name: build-${{ steps.date.outputs.date }}
        name: Build ${{ steps.date.outputs.date }}
        body: |
          Automated build from StarfireLab/SharpWeb fork.
          Build Date: ${{ steps.date.outputs.date }}
        files: |
          ./Artifacts/*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
